---
title: "Phyloseq PreProcessing"
author: "Calla Bush St George"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "../figures/02_PreProcessing/")
# Send any figure output to the 02_PreProcessing folder
```


# Load libraries
```{r load-libraries}
library("devtools")
#install_github("joey711/phyloseq")
library("phyloseq")
library("tidyverse")
```

# Goals

Here, we will process the data into a phyloseq object.

- ASV table
- Taxonomy table
- Track Reads (metadata)

Then, we will remove the following:

1. Remove Chloroplasts.
2. Remove Mitochondria.
3. Remove samples without "enough" reads.

Finally, write a data file of phyloseq output. 

# Load data

## ASV table
```{r load-ASV-table}
# First, load ASV table
load("data/01_DADA2/ASV_counts.RData")

# Inspect ASV_tab
head(asv_tab)[,1:5]

# Fix names
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1)
head(samples_fixed)

# re-write the ASV count file to fix names
colnames(asv_tab) <- samples_fixed

```

## Taxonomy table
```{r load-tax-table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t", skip = 1)
head(tax_df)

# fix column names
colnames(tax_df) <- c("asv_names", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ASV", "ASVseq")

head(tax_df)

#Taxonomy Table Matrix
tax_mat <-
tax_df %>%
  tibble::column_to_rownames(., var = "asv_names") %>%
  as.matrix()
```

## Track Reads Data
```{r load-track-reads}

```

# Handoff to phyloseq
```{r phyloseq-handoff}

```




